// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: im.proto
// Protobuf C++ Version: 7.34.1

#ifndef im_2eproto_2epb_2eh
#define im_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_im_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_im_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_im_2eproto;
}  // extern "C"
namespace im {
class GetChatHistoryRequest;
struct GetChatHistoryRequestDefaultTypeInternal;
extern GetChatHistoryRequestDefaultTypeInternal _GetChatHistoryRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GetChatHistoryRequest_class_data_;
class GetChatHistoryResponse;
struct GetChatHistoryResponseDefaultTypeInternal;
extern GetChatHistoryResponseDefaultTypeInternal _GetChatHistoryResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GetChatHistoryResponse_class_data_;
class MessageContent;
struct MessageContentDefaultTypeInternal;
extern MessageContentDefaultTypeInternal _MessageContent_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MessageContent_class_data_;
class MessageItem;
struct MessageItemDefaultTypeInternal;
extern MessageItemDefaultTypeInternal _MessageItem_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MessageItem_class_data_;
}  // namespace im
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace im {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED MessageContent final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:im.MessageContent) */ {
 public:
  inline MessageContent() : MessageContent(nullptr) {}
  ~MessageContent() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MessageContent* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MessageContent));
  }
#endif

  template <typename = void>
  explicit constexpr MessageContent(::google::protobuf::internal::ConstantInitialized);

  inline MessageContent(const MessageContent& from) : MessageContent(nullptr, from) {}
  inline MessageContent(MessageContent&& from) noexcept
      : MessageContent(nullptr, ::std::move(from)) {}
  inline MessageContent& operator=(const MessageContent& from) {
    CopyFrom(from);
    return *this;
  }
  inline MessageContent& operator=(MessageContent&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const MessageContent& default_instance() {
    return *reinterpret_cast<const MessageContent*>(
        &_MessageContent_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MessageContent& a, MessageContent& b) { a.Swap(&b); }
  inline void Swap(MessageContent* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MessageContent* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] MessageContent* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MessageContent>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MessageContent& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MessageContent& from) { MessageContent::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MessageContent* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "im.MessageContent"; }

  explicit MessageContent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MessageContent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MessageContent& from);
  MessageContent(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MessageContent&& from) noexcept
      : MessageContent(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 2,
    kMimeTypeFieldNumber = 3,
    kFidFieldNumber = 4,
    kTypeFieldNumber = 1,
  };
  // string data = 2;
  void clear_data() ;
  [[nodiscard]] const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // string mime_type = 3;
  void clear_mime_type() ;
  [[nodiscard]] const ::std::string& mime_type() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_mime_type(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_mime_type();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_mime_type();
  void set_allocated_mime_type(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_mime_type() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_mime_type(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_mime_type();

  public:
  // string fid = 4;
  void clear_fid() ;
  [[nodiscard]] const ::std::string& fid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_fid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_fid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_fid();
  void set_allocated_fid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_fid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_fid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_fid();

  public:
  // int32 type = 1;
  void clear_type() ;
  [[nodiscard]] ::int32_t type() const;
  void set_type(::int32_t value);

  private:
  ::int32_t _internal_type() const;
  void _internal_set_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:im.MessageContent)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 42,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MessageContent& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::google::protobuf::internal::ArenaStringPtr mime_type_;
    ::google::protobuf::internal::ArenaStringPtr fid_;
    ::int32_t type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_im_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MessageContent_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED GetChatHistoryRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:im.GetChatHistoryRequest) */ {
 public:
  inline GetChatHistoryRequest() : GetChatHistoryRequest(nullptr) {}
  ~GetChatHistoryRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetChatHistoryRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetChatHistoryRequest));
  }
#endif

  template <typename = void>
  explicit constexpr GetChatHistoryRequest(::google::protobuf::internal::ConstantInitialized);

  inline GetChatHistoryRequest(const GetChatHistoryRequest& from) : GetChatHistoryRequest(nullptr, from) {}
  inline GetChatHistoryRequest(GetChatHistoryRequest&& from) noexcept
      : GetChatHistoryRequest(nullptr, ::std::move(from)) {}
  inline GetChatHistoryRequest& operator=(const GetChatHistoryRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetChatHistoryRequest& operator=(GetChatHistoryRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const GetChatHistoryRequest& default_instance() {
    return *reinterpret_cast<const GetChatHistoryRequest*>(
        &_GetChatHistoryRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(GetChatHistoryRequest& a, GetChatHistoryRequest& b) { a.Swap(&b); }
  inline void Swap(GetChatHistoryRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetChatHistoryRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] GetChatHistoryRequest* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GetChatHistoryRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetChatHistoryRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetChatHistoryRequest& from) { GetChatHistoryRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GetChatHistoryRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "im.GetChatHistoryRequest"; }

  explicit GetChatHistoryRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GetChatHistoryRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GetChatHistoryRequest& from);
  GetChatHistoryRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GetChatHistoryRequest&& from) noexcept
      : GetChatHistoryRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimestampFieldNumber = 3,
    kFromUidFieldNumber = 1,
    kToUidFieldNumber = 2,
    kLoadSizeFieldNumber = 4,
  };
  // string timestamp = 3;
  void clear_timestamp() ;
  [[nodiscard]] const ::std::string& timestamp() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_timestamp(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_timestamp();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_timestamp();
  void set_allocated_timestamp(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_timestamp() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_timestamp();

  public:
  // int32 from_uid = 1;
  void clear_from_uid() ;
  [[nodiscard]] ::int32_t from_uid() const;
  void set_from_uid(::int32_t value);

  private:
  ::int32_t _internal_from_uid() const;
  void _internal_set_from_uid(::int32_t value);

  public:
  // int32 to_uid = 2;
  void clear_to_uid() ;
  [[nodiscard]] ::int32_t to_uid() const;
  void set_to_uid(::int32_t value);

  private:
  ::int32_t _internal_to_uid() const;
  void _internal_set_to_uid(::int32_t value);

  public:
  // int32 load_size = 4;
  void clear_load_size() ;
  [[nodiscard]] ::int32_t load_size() const;
  void set_load_size(::int32_t value);

  private:
  ::int32_t _internal_load_size() const;
  void _internal_set_load_size(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:im.GetChatHistoryRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 42,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GetChatHistoryRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr timestamp_;
    ::int32_t from_uid_;
    ::int32_t to_uid_;
    ::int32_t load_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_im_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GetChatHistoryRequest_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED MessageItem final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:im.MessageItem) */ {
 public:
  inline MessageItem() : MessageItem(nullptr) {}
  ~MessageItem() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MessageItem* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MessageItem));
  }
#endif

  template <typename = void>
  explicit constexpr MessageItem(::google::protobuf::internal::ConstantInitialized);

  inline MessageItem(const MessageItem& from) : MessageItem(nullptr, from) {}
  inline MessageItem(MessageItem&& from) noexcept
      : MessageItem(nullptr, ::std::move(from)) {}
  inline MessageItem& operator=(const MessageItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline MessageItem& operator=(MessageItem&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const MessageItem& default_instance() {
    return *reinterpret_cast<const MessageItem*>(
        &_MessageItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(MessageItem& a, MessageItem& b) { a.Swap(&b); }
  inline void Swap(MessageItem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MessageItem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] MessageItem* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MessageItem>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MessageItem& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MessageItem& from) { MessageItem::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MessageItem* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "im.MessageItem"; }

  explicit MessageItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MessageItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MessageItem& from);
  MessageItem(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MessageItem&& from) noexcept
      : MessageItem(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kTimestampFieldNumber = 4,
    kContentFieldNumber = 6,
    kToIdFieldNumber = 2,
    kFromIdFieldNumber = 3,
    kEnvFieldNumber = 5,
  };
  // string id = 1;
  void clear_id() ;
  [[nodiscard]] const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // string timestamp = 4;
  void clear_timestamp() ;
  [[nodiscard]] const ::std::string& timestamp() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_timestamp(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_timestamp();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_timestamp();
  void set_allocated_timestamp(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_timestamp() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_timestamp();

  public:
  // .im.MessageContent content = 6;
  [[nodiscard]] bool has_content()
      const;
  void clear_content() ;
  [[nodiscard]] const ::im::MessageContent& content() const;
  [[nodiscard]] ::im::MessageContent* PROTOBUF_NULLABLE release_content();
  ::im::MessageContent* PROTOBUF_NONNULL mutable_content();
  void set_allocated_content(::im::MessageContent* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_content(::im::MessageContent* PROTOBUF_NULLABLE value);
  ::im::MessageContent* PROTOBUF_NULLABLE unsafe_arena_release_content();

  private:
  const ::im::MessageContent& _internal_content() const;
  ::im::MessageContent* PROTOBUF_NONNULL _internal_mutable_content();

  public:
  // int32 to_id = 2;
  void clear_to_id() ;
  [[nodiscard]] ::int32_t to_id() const;
  void set_to_id(::int32_t value);

  private:
  ::int32_t _internal_to_id() const;
  void _internal_set_to_id(::int32_t value);

  public:
  // int32 from_id = 3;
  void clear_from_id() ;
  [[nodiscard]] ::int32_t from_id() const;
  void set_from_id(::int32_t value);

  private:
  ::int32_t _internal_from_id() const;
  void _internal_set_from_id(::int32_t value);

  public:
  // int32 env = 5;
  void clear_env() ;
  [[nodiscard]] ::int32_t env() const;
  void set_env(::int32_t value);

  private:
  ::int32_t _internal_env() const;
  void _internal_set_env(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:im.MessageItem)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   1, 34,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MessageItem& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr timestamp_;
    ::im::MessageContent* PROTOBUF_NULLABLE content_;
    ::int32_t to_id_;
    ::int32_t from_id_;
    ::int32_t env_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_im_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MessageItem_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED GetChatHistoryResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:im.GetChatHistoryResponse) */ {
 public:
  inline GetChatHistoryResponse() : GetChatHistoryResponse(nullptr) {}
  ~GetChatHistoryResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetChatHistoryResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetChatHistoryResponse));
  }
#endif

  template <typename = void>
  explicit constexpr GetChatHistoryResponse(::google::protobuf::internal::ConstantInitialized);

  inline GetChatHistoryResponse(const GetChatHistoryResponse& from) : GetChatHistoryResponse(nullptr, from) {}
  inline GetChatHistoryResponse(GetChatHistoryResponse&& from) noexcept
      : GetChatHistoryResponse(nullptr, ::std::move(from)) {}
  inline GetChatHistoryResponse& operator=(const GetChatHistoryResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetChatHistoryResponse& operator=(GetChatHistoryResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const GetChatHistoryResponse& default_instance() {
    return *reinterpret_cast<const GetChatHistoryResponse*>(
        &_GetChatHistoryResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(GetChatHistoryResponse& a, GetChatHistoryResponse& b) { a.Swap(&b); }
  inline void Swap(GetChatHistoryResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetChatHistoryResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] GetChatHistoryResponse* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GetChatHistoryResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetChatHistoryResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetChatHistoryResponse& from) { GetChatHistoryResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GetChatHistoryResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "im.GetChatHistoryResponse"; }

  explicit GetChatHistoryResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GetChatHistoryResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GetChatHistoryResponse& from);
  GetChatHistoryResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GetChatHistoryResponse&& from) noexcept
      : GetChatHistoryResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessagesFieldNumber = 3,
    kFromUidFieldNumber = 1,
    kToUidFieldNumber = 2,
    kHasMoreFieldNumber = 4,
  };
  // repeated .im.MessageItem messages = 3;
  [[nodiscard]] int messages_size()
      const;
  private:
  int _internal_messages_size() const;

  public:
  void clear_messages() ;
  [[nodiscard]] ::im::MessageItem* PROTOBUF_NONNULL mutable_messages(int index);
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::im::MessageItem>* PROTOBUF_NONNULL
  mutable_messages();

  private:
  const ::google::protobuf::RepeatedPtrField<::im::MessageItem>& _internal_messages() const;
  ::google::protobuf::RepeatedPtrField<::im::MessageItem>* PROTOBUF_NONNULL _internal_mutable_messages();
  public:
  [[nodiscard]] const ::im::MessageItem& messages(int index) const;
  ::im::MessageItem* PROTOBUF_NONNULL add_messages();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::im::MessageItem>& messages()
      const;
  // int32 from_uid = 1;
  void clear_from_uid() ;
  [[nodiscard]] ::int32_t from_uid() const;
  void set_from_uid(::int32_t value);

  private:
  ::int32_t _internal_from_uid() const;
  void _internal_set_from_uid(::int32_t value);

  public:
  // int32 to_uid = 2;
  void clear_to_uid() ;
  [[nodiscard]] ::int32_t to_uid() const;
  void set_to_uid(::int32_t value);

  private:
  ::int32_t _internal_to_uid() const;
  void _internal_set_to_uid(::int32_t value);

  public:
  // bool has_more = 4;
  void clear_has_more() ;
  [[nodiscard]] bool has_more() const;
  void set_has_more(bool value);

  private:
  bool _internal_has_more() const;
  void _internal_set_has_more(bool value);

  public:
  // @@protoc_insertion_point(class_scope:im.GetChatHistoryResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GetChatHistoryResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::im::MessageItem > messages_;
    ::int32_t from_uid_;
    ::int32_t to_uid_;
    bool has_more_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_im_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GetChatHistoryResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MessageContent

// int32 type = 1;
inline void MessageContent::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t MessageContent::type() const {
  // @@protoc_insertion_point(field_get:im.MessageContent.type)
  return _internal_type();
}
inline void MessageContent::set_type(::int32_t value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:im.MessageContent.type)
}
inline ::int32_t MessageContent::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_;
}
inline void MessageContent::_internal_set_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// string data = 2;
inline void MessageContent::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& MessageContent::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:im.MessageContent.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MessageContent::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.data_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:im.MessageContent.data)
}
inline ::std::string* PROTOBUF_NONNULL MessageContent::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:im.MessageContent.data)
  return _s;
}
inline const ::std::string& MessageContent::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void MessageContent::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MessageContent::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MessageContent::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:im.MessageContent.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void MessageContent::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:im.MessageContent.data)
}

// string mime_type = 3;
inline void MessageContent::clear_mime_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mime_type_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& MessageContent::mime_type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:im.MessageContent.mime_type)
  return _internal_mime_type();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MessageContent::set_mime_type(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.mime_type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:im.MessageContent.mime_type)
}
inline ::std::string* PROTOBUF_NONNULL MessageContent::mutable_mime_type()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_mime_type();
  // @@protoc_insertion_point(field_mutable:im.MessageContent.mime_type)
  return _s;
}
inline const ::std::string& MessageContent::_internal_mime_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mime_type_.Get();
}
inline void MessageContent::_internal_set_mime_type(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mime_type_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MessageContent::_internal_mutable_mime_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.mime_type_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MessageContent::release_mime_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:im.MessageContent.mime_type)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.mime_type_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.mime_type_.Set("", GetArena());
  }
  return released;
}
inline void MessageContent::set_allocated_mime_type(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.mime_type_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.mime_type_.IsDefault()) {
    _impl_.mime_type_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:im.MessageContent.mime_type)
}

// string fid = 4;
inline void MessageContent::clear_fid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& MessageContent::fid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:im.MessageContent.fid)
  return _internal_fid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MessageContent::set_fid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.fid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:im.MessageContent.fid)
}
inline ::std::string* PROTOBUF_NONNULL MessageContent::mutable_fid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_fid();
  // @@protoc_insertion_point(field_mutable:im.MessageContent.fid)
  return _s;
}
inline const ::std::string& MessageContent::_internal_fid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fid_.Get();
}
inline void MessageContent::_internal_set_fid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MessageContent::_internal_mutable_fid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.fid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MessageContent::release_fid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:im.MessageContent.fid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.fid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.fid_.Set("", GetArena());
  }
  return released;
}
inline void MessageContent::set_allocated_fid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.fid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.fid_.IsDefault()) {
    _impl_.fid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:im.MessageContent.fid)
}

// -------------------------------------------------------------------

// MessageItem

// string id = 1;
inline void MessageItem::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& MessageItem::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:im.MessageItem.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MessageItem::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:im.MessageItem.id)
}
inline ::std::string* PROTOBUF_NONNULL MessageItem::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:im.MessageItem.id)
  return _s;
}
inline const ::std::string& MessageItem::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void MessageItem::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MessageItem::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MessageItem::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:im.MessageItem.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void MessageItem::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:im.MessageItem.id)
}

// int32 to_id = 2;
inline void MessageItem::clear_to_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.to_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t MessageItem::to_id() const {
  // @@protoc_insertion_point(field_get:im.MessageItem.to_id)
  return _internal_to_id();
}
inline void MessageItem::set_to_id(::int32_t value) {
  _internal_set_to_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:im.MessageItem.to_id)
}
inline ::int32_t MessageItem::_internal_to_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.to_id_;
}
inline void MessageItem::_internal_set_to_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.to_id_ = value;
}

// int32 from_id = 3;
inline void MessageItem::clear_from_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.from_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t MessageItem::from_id() const {
  // @@protoc_insertion_point(field_get:im.MessageItem.from_id)
  return _internal_from_id();
}
inline void MessageItem::set_from_id(::int32_t value) {
  _internal_set_from_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:im.MessageItem.from_id)
}
inline ::int32_t MessageItem::_internal_from_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.from_id_;
}
inline void MessageItem::_internal_set_from_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.from_id_ = value;
}

// string timestamp = 4;
inline void MessageItem::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& MessageItem::timestamp() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:im.MessageItem.timestamp)
  return _internal_timestamp();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MessageItem::set_timestamp(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.timestamp_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:im.MessageItem.timestamp)
}
inline ::std::string* PROTOBUF_NONNULL MessageItem::mutable_timestamp()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:im.MessageItem.timestamp)
  return _s;
}
inline const ::std::string& MessageItem::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_.Get();
}
inline void MessageItem::_internal_set_timestamp(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MessageItem::_internal_mutable_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.timestamp_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MessageItem::release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:im.MessageItem.timestamp)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.timestamp_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.timestamp_.Set("", GetArena());
  }
  return released;
}
inline void MessageItem::set_allocated_timestamp(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.timestamp_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:im.MessageItem.timestamp)
}

// int32 env = 5;
inline void MessageItem::clear_env() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.env_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t MessageItem::env() const {
  // @@protoc_insertion_point(field_get:im.MessageItem.env)
  return _internal_env();
}
inline void MessageItem::set_env(::int32_t value) {
  _internal_set_env(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:im.MessageItem.env)
}
inline ::int32_t MessageItem::_internal_env() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.env_;
}
inline void MessageItem::_internal_set_env(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.env_ = value;
}

// .im.MessageContent content = 6;
inline bool MessageItem::has_content() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.content_ != nullptr);
  return value;
}
inline void MessageItem::clear_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.content_ != nullptr) _impl_.content_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::im::MessageContent& MessageItem::_internal_content() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::im::MessageContent* p = _impl_.content_;
  return p != nullptr ? *p : reinterpret_cast<const ::im::MessageContent&>(::im::_MessageContent_default_instance_);
}
inline const ::im::MessageContent& MessageItem::content() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:im.MessageItem.content)
  return _internal_content();
}
inline void MessageItem::unsafe_arena_set_allocated_content(
    ::im::MessageContent* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.content_);
  }
  _impl_.content_ = reinterpret_cast<::im::MessageContent*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:im.MessageItem.content)
}
inline ::im::MessageContent* PROTOBUF_NULLABLE MessageItem::release_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::im::MessageContent* released = _impl_.content_;
  _impl_.content_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::im::MessageContent* PROTOBUF_NULLABLE MessageItem::unsafe_arena_release_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:im.MessageItem.content)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::im::MessageContent* temp = _impl_.content_;
  _impl_.content_ = nullptr;
  return temp;
}
inline ::im::MessageContent* PROTOBUF_NONNULL MessageItem::_internal_mutable_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.content_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::im::MessageContent>(GetArena());
    _impl_.content_ = reinterpret_cast<::im::MessageContent*>(p);
  }
  return _impl_.content_;
}
inline ::im::MessageContent* PROTOBUF_NONNULL MessageItem::mutable_content()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::im::MessageContent* _msg = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:im.MessageItem.content)
  return _msg;
}
inline void MessageItem::set_allocated_content(::im::MessageContent* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.content_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.content_ = reinterpret_cast<::im::MessageContent*>(value);
  // @@protoc_insertion_point(field_set_allocated:im.MessageItem.content)
}

// -------------------------------------------------------------------

// GetChatHistoryRequest

// int32 from_uid = 1;
inline void GetChatHistoryRequest::clear_from_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.from_uid_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t GetChatHistoryRequest::from_uid() const {
  // @@protoc_insertion_point(field_get:im.GetChatHistoryRequest.from_uid)
  return _internal_from_uid();
}
inline void GetChatHistoryRequest::set_from_uid(::int32_t value) {
  _internal_set_from_uid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:im.GetChatHistoryRequest.from_uid)
}
inline ::int32_t GetChatHistoryRequest::_internal_from_uid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.from_uid_;
}
inline void GetChatHistoryRequest::_internal_set_from_uid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.from_uid_ = value;
}

// int32 to_uid = 2;
inline void GetChatHistoryRequest::clear_to_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.to_uid_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t GetChatHistoryRequest::to_uid() const {
  // @@protoc_insertion_point(field_get:im.GetChatHistoryRequest.to_uid)
  return _internal_to_uid();
}
inline void GetChatHistoryRequest::set_to_uid(::int32_t value) {
  _internal_set_to_uid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:im.GetChatHistoryRequest.to_uid)
}
inline ::int32_t GetChatHistoryRequest::_internal_to_uid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.to_uid_;
}
inline void GetChatHistoryRequest::_internal_set_to_uid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.to_uid_ = value;
}

// string timestamp = 3;
inline void GetChatHistoryRequest::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& GetChatHistoryRequest::timestamp() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:im.GetChatHistoryRequest.timestamp)
  return _internal_timestamp();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void GetChatHistoryRequest::set_timestamp(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.timestamp_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:im.GetChatHistoryRequest.timestamp)
}
inline ::std::string* PROTOBUF_NONNULL GetChatHistoryRequest::mutable_timestamp()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:im.GetChatHistoryRequest.timestamp)
  return _s;
}
inline const ::std::string& GetChatHistoryRequest::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_.Get();
}
inline void GetChatHistoryRequest::_internal_set_timestamp(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL GetChatHistoryRequest::_internal_mutable_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.timestamp_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE GetChatHistoryRequest::release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:im.GetChatHistoryRequest.timestamp)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.timestamp_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.timestamp_.Set("", GetArena());
  }
  return released;
}
inline void GetChatHistoryRequest::set_allocated_timestamp(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.timestamp_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:im.GetChatHistoryRequest.timestamp)
}

// int32 load_size = 4;
inline void GetChatHistoryRequest::clear_load_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.load_size_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t GetChatHistoryRequest::load_size() const {
  // @@protoc_insertion_point(field_get:im.GetChatHistoryRequest.load_size)
  return _internal_load_size();
}
inline void GetChatHistoryRequest::set_load_size(::int32_t value) {
  _internal_set_load_size(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:im.GetChatHistoryRequest.load_size)
}
inline ::int32_t GetChatHistoryRequest::_internal_load_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.load_size_;
}
inline void GetChatHistoryRequest::_internal_set_load_size(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.load_size_ = value;
}

// -------------------------------------------------------------------

// GetChatHistoryResponse

// int32 from_uid = 1;
inline void GetChatHistoryResponse::clear_from_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.from_uid_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t GetChatHistoryResponse::from_uid() const {
  // @@protoc_insertion_point(field_get:im.GetChatHistoryResponse.from_uid)
  return _internal_from_uid();
}
inline void GetChatHistoryResponse::set_from_uid(::int32_t value) {
  _internal_set_from_uid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:im.GetChatHistoryResponse.from_uid)
}
inline ::int32_t GetChatHistoryResponse::_internal_from_uid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.from_uid_;
}
inline void GetChatHistoryResponse::_internal_set_from_uid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.from_uid_ = value;
}

// int32 to_uid = 2;
inline void GetChatHistoryResponse::clear_to_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.to_uid_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t GetChatHistoryResponse::to_uid() const {
  // @@protoc_insertion_point(field_get:im.GetChatHistoryResponse.to_uid)
  return _internal_to_uid();
}
inline void GetChatHistoryResponse::set_to_uid(::int32_t value) {
  _internal_set_to_uid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:im.GetChatHistoryResponse.to_uid)
}
inline ::int32_t GetChatHistoryResponse::_internal_to_uid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.to_uid_;
}
inline void GetChatHistoryResponse::_internal_set_to_uid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.to_uid_ = value;
}

// repeated .im.MessageItem messages = 3;
inline int GetChatHistoryResponse::_internal_messages_size() const {
  return _internal_messages().size();
}
inline int GetChatHistoryResponse::messages_size() const {
  return _internal_messages_size();
}
inline void GetChatHistoryResponse::clear_messages() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.messages_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::im::MessageItem* PROTOBUF_NONNULL GetChatHistoryResponse::mutable_messages(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:im.GetChatHistoryResponse.messages)
  return _internal_mutable_messages()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::im::MessageItem>* PROTOBUF_NONNULL GetChatHistoryResponse::mutable_messages()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:im.GetChatHistoryResponse.messages)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_messages();
}
inline const ::im::MessageItem& GetChatHistoryResponse::messages(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:im.GetChatHistoryResponse.messages)
  return _internal_messages().Get(index);
}
inline ::im::MessageItem* PROTOBUF_NONNULL GetChatHistoryResponse::add_messages()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::im::MessageItem* _add =
      _internal_mutable_messages()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:im.GetChatHistoryResponse.messages)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::im::MessageItem>& GetChatHistoryResponse::messages() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:im.GetChatHistoryResponse.messages)
  return _internal_messages();
}
inline const ::google::protobuf::RepeatedPtrField<::im::MessageItem>&
GetChatHistoryResponse::_internal_messages() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.messages_;
}
inline ::google::protobuf::RepeatedPtrField<::im::MessageItem>* PROTOBUF_NONNULL
GetChatHistoryResponse::_internal_mutable_messages() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.messages_;
}

// bool has_more = 4;
inline void GetChatHistoryResponse::clear_has_more() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.has_more_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline bool GetChatHistoryResponse::has_more() const {
  // @@protoc_insertion_point(field_get:im.GetChatHistoryResponse.has_more)
  return _internal_has_more();
}
inline void GetChatHistoryResponse::set_has_more(bool value) {
  _internal_set_has_more(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:im.GetChatHistoryResponse.has_more)
}
inline bool GetChatHistoryResponse::_internal_has_more() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.has_more_;
}
inline void GetChatHistoryResponse::_internal_set_has_more(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.has_more_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace im


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // im_2eproto_2epb_2eh
