// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: im.proto
// Protobuf C++ Version: 7.34.1

#include "im.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace im {

inline constexpr MessageContent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        mime_type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        fid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_{0} {}

template <typename>
constexpr MessageContent::MessageContent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MessageContent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct MessageContentDefaultTypeInternal {
  constexpr MessageContentDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageContentDefaultTypeInternal() {}
  union {
    MessageContent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageContentDefaultTypeInternal _MessageContent_default_instance_;

inline constexpr MessageItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        content_{nullptr},
        to_id_{0},
        from_id_{0},
        env_{0} {}

template <typename>
constexpr MessageItem::MessageItem(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MessageItem_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct MessageItemDefaultTypeInternal {
  constexpr MessageItemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageItemDefaultTypeInternal() {}
  union {
    MessageItem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageItemDefaultTypeInternal _MessageItem_default_instance_;
}  // namespace im
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_im_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_im_2eproto = nullptr;
const ::uint32_t
    TableStruct_im_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::im::MessageContent, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::im::MessageContent, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::im::MessageContent, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::im::MessageContent, _impl_.mime_type_),
        PROTOBUF_FIELD_OFFSET(::im::MessageContent, _impl_.fid_),
        3,
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::im::MessageItem, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::im::MessageItem, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::im::MessageItem, _impl_.to_id_),
        PROTOBUF_FIELD_OFFSET(::im::MessageItem, _impl_.from_id_),
        PROTOBUF_FIELD_OFFSET(::im::MessageItem, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::im::MessageItem, _impl_.env_),
        PROTOBUF_FIELD_OFFSET(::im::MessageItem, _impl_.content_),
        0,
        3,
        4,
        1,
        5,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::im::MessageContent)},
        {11, sizeof(::im::MessageItem)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::im::_MessageContent_default_instance_._instance,
    &::im::_MessageItem_default_instance_._instance,
};
const char descriptor_table_protodef_im_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\010im.proto\022\002im\"L\n\016MessageContent\022\014\n\004type"
    "\030\001 \001(\005\022\014\n\004data\030\002 \001(\t\022\021\n\tmime_type\030\003 \001(\t\022"
    "\013\n\003fid\030\004 \001(\t\"~\n\013MessageItem\022\n\n\002id\030\001 \001(\t\022"
    "\r\n\005to_id\030\002 \001(\005\022\017\n\007from_id\030\003 \001(\005\022\021\n\ttimes"
    "tamp\030\004 \001(\t\022\013\n\003env\030\005 \001(\005\022#\n\007content\030\006 \001(\013"
    "2\022.im.MessageContentb\006proto3"
};
static ::absl::once_flag descriptor_table_im_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_im_2eproto = {
    false,
    false,
    228,
    descriptor_table_protodef_im_2eproto,
    "im.proto",
    &descriptor_table_im_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_im_2eproto::offsets,
    file_level_enum_descriptors_im_2eproto,
    file_level_service_descriptors_im_2eproto,
};
namespace im {
// ===================================================================

class MessageContent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<MessageContent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MessageContent, _impl_._has_bits_);
};

MessageContent::MessageContent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MessageContent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:im.MessageContent)
}
PROTOBUF_NDEBUG_INLINE MessageContent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::im::MessageContent& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        data_(arena, from.data_),
        mime_type_(arena, from.mime_type_),
        fid_(arena, from.fid_) {}

MessageContent::MessageContent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MessageContent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MessageContent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MessageContent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.type_ = from._impl_.type_;

  // @@protoc_insertion_point(copy_constructor:im.MessageContent)
}
PROTOBUF_NDEBUG_INLINE MessageContent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        data_(arena),
        mime_type_(arena),
        fid_(arena) {}

inline void MessageContent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.type_ = {};
}
MessageContent::~MessageContent() {
  // @@protoc_insertion_point(destructor:im.MessageContent)
  SharedDtor(*this);
}
inline void MessageContent::SharedDtor(MessageLite& self) {
  MessageContent& this_ = static_cast<MessageContent&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.data_.Destroy();
  this_._impl_.mime_type_.Destroy();
  this_._impl_.fid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MessageContent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MessageContent(arena);
}
constexpr auto MessageContent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MessageContent),
                                            alignof(MessageContent));
}
constexpr auto MessageContent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MessageContent_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &MessageContent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MessageContent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MessageContent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MessageContent>(), &MessageContent::ByteSizeLong,
              &MessageContent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MessageContent, _impl_._cached_size_),
          false,
      },
      &MessageContent::kDescriptorMethods,
      &descriptor_table_im_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MessageContent_class_data_ =
        MessageContent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
MessageContent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MessageContent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MessageContent_class_data_.tc_table);
  return MessageContent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 42, 2>
MessageContent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MessageContent, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    MessageContent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::im::MessageContent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string fid = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 2, 0,
      PROTOBUF_FIELD_OFFSET(MessageContent, _impl_.fid_)}},
    // int32 type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MessageContent, _impl_.type_), 3>(),
     {8, 3, 0,
      PROTOBUF_FIELD_OFFSET(MessageContent, _impl_.type_)}},
    // string data = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(MessageContent, _impl_.data_)}},
    // string mime_type = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(MessageContent, _impl_.mime_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 type = 1;
    {PROTOBUF_FIELD_OFFSET(MessageContent, _impl_.type_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string data = 2;
    {PROTOBUF_FIELD_OFFSET(MessageContent, _impl_.data_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string mime_type = 3;
    {PROTOBUF_FIELD_OFFSET(MessageContent, _impl_.mime_type_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string fid = 4;
    {PROTOBUF_FIELD_OFFSET(MessageContent, _impl_.fid_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\0\4\11\3\0\0\0"
    "im.MessageContent"
    "data"
    "mime_type"
    "fid"
  }},
};
PROTOBUF_NOINLINE void MessageContent::Clear() {
// @@protoc_insertion_point(message_clear_start:im.MessageContent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.data_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.mime_type_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.fid_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MessageContent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MessageContent& this_ = static_cast<const MessageContent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MessageContent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MessageContent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:im.MessageContent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_type() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_type(), target);
    }
  }

  // string data = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_data().empty()) {
      const ::std::string& _s = this_._internal_data();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "im.MessageContent.data");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string mime_type = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_mime_type().empty()) {
      const ::std::string& _s = this_._internal_mime_type();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "im.MessageContent.mime_type");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string fid = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_fid().empty()) {
      const ::std::string& _s = this_._internal_fid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "im.MessageContent.fid");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:im.MessageContent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MessageContent::ByteSizeLong(const MessageLite& base) {
  const MessageContent& this_ = static_cast<const MessageContent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MessageContent::ByteSizeLong() const {
  const MessageContent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:im.MessageContent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string data = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_data());
      }
    }
    // string mime_type = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_mime_type().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_mime_type());
      }
    }
    // string fid = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_fid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_fid());
      }
    }
    // int32 type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_type() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_type());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MessageContent::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<MessageContent*>(&to_msg);
  auto& from = static_cast<const MessageContent&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:im.MessageContent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_data().empty()) {
        _this->_internal_set_data(from._internal_data());
      } else {
        if (_this->_impl_.data_.IsDefault()) {
          _this->_internal_set_data("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_mime_type().empty()) {
        _this->_internal_set_mime_type(from._internal_mime_type());
      } else {
        if (_this->_impl_.mime_type_.IsDefault()) {
          _this->_internal_set_mime_type("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_fid().empty()) {
        _this->_internal_set_fid(from._internal_fid());
      } else {
        if (_this->_impl_.fid_.IsDefault()) {
          _this->_internal_set_fid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_type() != 0) {
        _this->_impl_.type_ = from._impl_.type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void MessageContent::CopyFrom(const MessageContent& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:im.MessageContent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MessageContent::InternalSwap(MessageContent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.mime_type_, &other->_impl_.mime_type_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.fid_, &other->_impl_.fid_, arena);
  swap(_impl_.type_, other->_impl_.type_);
}

::google::protobuf::Metadata MessageContent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MessageItem::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<MessageItem>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MessageItem, _impl_._has_bits_);
};

MessageItem::MessageItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MessageItem_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:im.MessageItem)
}
PROTOBUF_NDEBUG_INLINE MessageItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::im::MessageItem& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        id_(arena, from.id_),
        timestamp_(arena, from.timestamp_) {}

MessageItem::MessageItem(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MessageItem& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MessageItem_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MessageItem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.content_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.content_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, to_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, to_id_),
           offsetof(Impl_, env_) -
               offsetof(Impl_, to_id_) +
               sizeof(Impl_::env_));

  // @@protoc_insertion_point(copy_constructor:im.MessageItem)
}
PROTOBUF_NDEBUG_INLINE MessageItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        id_(arena),
        timestamp_(arena) {}

inline void MessageItem::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, content_),
           0,
           offsetof(Impl_, env_) -
               offsetof(Impl_, content_) +
               sizeof(Impl_::env_));
}
MessageItem::~MessageItem() {
  // @@protoc_insertion_point(destructor:im.MessageItem)
  SharedDtor(*this);
}
inline void MessageItem::SharedDtor(MessageLite& self) {
  MessageItem& this_ = static_cast<MessageItem&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.timestamp_.Destroy();
  delete this_._impl_.content_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MessageItem::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MessageItem(arena);
}
constexpr auto MessageItem::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MessageItem),
                                            alignof(MessageItem));
}
constexpr auto MessageItem::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MessageItem_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &MessageItem::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MessageItem>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MessageItem::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MessageItem>(), &MessageItem::ByteSizeLong,
              &MessageItem::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MessageItem, _impl_._cached_size_),
          false,
      },
      &MessageItem::kDescriptorMethods,
      &descriptor_table_im_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MessageItem_class_data_ =
        MessageItem::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
MessageItem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MessageItem_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MessageItem_class_data_.tc_table);
  return MessageItem_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 1, 34, 2>
MessageItem::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MessageItem, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    MessageItem_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::im::MessageItem>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.id_)}},
    // int32 to_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MessageItem, _impl_.to_id_), 3>(),
     {16, 3, 0,
      PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.to_id_)}},
    // int32 from_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MessageItem, _impl_.from_id_), 4>(),
     {24, 4, 0,
      PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.from_id_)}},
    // string timestamp = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.timestamp_)}},
    // int32 env = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MessageItem, _impl_.env_), 5>(),
     {40, 5, 0,
      PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.env_)}},
    // .im.MessageContent content = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 2, 0,
      PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.content_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 to_id = 2;
    {PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.to_id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 from_id = 3;
    {PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.from_id_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string timestamp = 4;
    {PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.timestamp_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 env = 5;
    {PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.env_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // .im.MessageContent content = 6;
    {PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.content_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::im::MessageContent>()},
  }},
  {{
    "\16\2\0\0\11\0\0\0"
    "im.MessageItem"
    "id"
    "timestamp"
  }},
};
PROTOBUF_NOINLINE void MessageItem::Clear() {
// @@protoc_insertion_point(message_clear_start:im.MessageItem)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.timestamp_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.content_ != nullptr);
      _impl_.content_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000038U)) {
    ::memset(&_impl_.to_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.env_) -
        reinterpret_cast<char*>(&_impl_.to_id_)) + sizeof(_impl_.env_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MessageItem::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MessageItem& this_ = static_cast<const MessageItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MessageItem::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MessageItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:im.MessageItem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_id().empty()) {
      const ::std::string& _s = this_._internal_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "im.MessageItem.id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int32 to_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_to_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_to_id(), target);
    }
  }

  // int32 from_id = 3;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_from_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_from_id(), target);
    }
  }

  // string timestamp = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_timestamp().empty()) {
      const ::std::string& _s = this_._internal_timestamp();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "im.MessageItem.timestamp");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // int32 env = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_env() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
              stream, this_._internal_env(), target);
    }
  }

  // .im.MessageContent content = 6;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, *this_._impl_.content_, this_._impl_.content_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:im.MessageItem)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MessageItem::ByteSizeLong(const MessageLite& base) {
  const MessageItem& this_ = static_cast<const MessageItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MessageItem::ByteSizeLong() const {
  const MessageItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:im.MessageItem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    // string id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_id());
      }
    }
    // string timestamp = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_timestamp().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_timestamp());
      }
    }
    // .im.MessageContent content = 6;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.content_);
    }
    // int32 to_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_to_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_to_id());
      }
    }
    // int32 from_id = 3;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_from_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_from_id());
      }
    }
    // int32 env = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_env() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_env());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MessageItem::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<MessageItem*>(&to_msg);
  auto& from = static_cast<const MessageItem&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:im.MessageItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_id().empty()) {
        _this->_internal_set_id(from._internal_id());
      } else {
        if (_this->_impl_.id_.IsDefault()) {
          _this->_internal_set_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_timestamp().empty()) {
        _this->_internal_set_timestamp(from._internal_timestamp());
      } else {
        if (_this->_impl_.timestamp_.IsDefault()) {
          _this->_internal_set_timestamp("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.content_ != nullptr);
      if (_this->_impl_.content_ == nullptr) {
        _this->_impl_.content_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.content_);
      } else {
        _this->_impl_.content_->MergeFrom(*from._impl_.content_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_to_id() != 0) {
        _this->_impl_.to_id_ = from._impl_.to_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_from_id() != 0) {
        _this->_impl_.from_id_ = from._impl_.from_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_env() != 0) {
        _this->_impl_.env_ = from._impl_.env_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void MessageItem::CopyFrom(const MessageItem& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:im.MessageItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MessageItem::InternalSwap(MessageItem* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.timestamp_, &other->_impl_.timestamp_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.env_)
      + sizeof(MessageItem::_impl_.env_)
      - PROTOBUF_FIELD_OFFSET(MessageItem, _impl_.content_)>(
          reinterpret_cast<char*>(&_impl_.content_),
          reinterpret_cast<char*>(&other->_impl_.content_));
}

::google::protobuf::Metadata MessageItem::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace im
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_im_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
